sudo: false
language: go
go:
  - 1.20.x
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
env:
  global:
    - REPO=$(basename $TRAVIS_REPO_SLUG)
    - TAG=$(git rev-parse --short HEAD)
    - AUTHOR=$(git --no-pager show -s --format='%an')
    - GOPRIVATE=github.com/gametimesf
before_install:
  # GITHUB_ACCESS_TOKEN for 'gametime-travis-ci' user (defined as env variable on Travis)
  - git config --global url."https://${GITHUB_ACCESS_TOKEN}@github.com/gametimesf".insteadOf "https://github.com/gametimesf"
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  - go install github.com/daixiang0/gci@latest
script:
  - make unit
